FROM ubuntu:24.04

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y sudo vim locales curl wget iputils-ping iptables ipset dnsutils jq iproute2 git ffmpeg

# dockerコンテナ内で日本語が入力できないため設定します。
RUN locale-gen ja_JP.UTF-8
ENV TERM=xterm-256color
ENV LANG=ja_JP.UTF-8
ENV TZ=Asia/Tokyo

ENV DISABLE_TELEMETRY=1
ENV CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
ENV DISABLE_AUTOUPDATER=true

# ubuntuユーザーをsudoグループから明示的に削除してsudo実行を防止
RUN gpasswd -d ubuntu sudo

# ubuntuユーザーのホームディレクトリに.hushloginファイルを作成してMOTDを抑制
# .hushloginファイルが無いと下記のメッセージが表示されます。
# To run a command as administrator (user "root"), use "sudo <command>".
# See "man sudo_root" for details.
RUN touch /home/ubuntu/.hushlogin
RUN chown ubuntu:ubuntu /home/ubuntu/.hushlogin

USER ubuntu

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

RUN bash -c "source $HOME/.nvm/nvm.sh && \
nvm install 24 && \
nvm use 24 && \
nvm alias default 24 && \
npm install -g npm \
"
